export type LandmarkIcon =
  | 'art'
  | 'heritage'
  | 'river'
  | 'nature'
  | 'community'
  | 'mobility';

export type Landmark = {
  id: string;
  name: string;
  shortName: string;
  icon: LandmarkIcon;
  glyph: string;
  color: string;
  coordinates: [number, number];
  zoom: number;
  pitch: number;
  bearing: number;
  eyebrow: string;
  fact: string;
  valuationLens: string;
  source: string;
  challenge: {
    prompt: string;
    choices: string[];
    answer: number;
    explanation: string;
  };
};

export const landmarks: Landmark[] = [
  {
    id: 'parques-del-rio',
    name: 'Parques del Río',
    shortName: 'Parques del Río',
    icon: 'river',
    glyph: '≈',
    color: '#168fc4',
    coordinates: [-75.5775, 6.2446],
    zoom: 16.7,
    pitch: 67,
    bearing: -18,
    eyebrow: 'Río y espacio público',
    fact: 'El parque integra 71.800 m² de espacio público, 3,3 km de ciclorruta, 8 km de senderos peatonales y 2.600 árboles.',
    valuationLens: 'La recuperación ambiental, la conectividad peatonal y las zonas de estancia cambian la percepción de localización y las dinámicas del suelo cercano.',
    source: 'Alcaldía de Medellín · Infraestructura Física',
    challenge: {
      prompt: '¿Qué atributo territorial describe mejor el efecto de Parques del Río?',
      choices: ['Aislamiento vial', 'Integración de espacio público y movilidad', 'Reducción del espacio verde'],
      answer: 1,
      explanation: 'El proyecto articula movilidad, paisaje, recreación y recuperación ambiental alrededor del río.',
    },
  },
  {
    id: 'pueblito-paisa',
    name: 'Pueblito Paisa y Cerro Nutibara',
    shortName: 'Pueblito Paisa',
    icon: 'heritage',
    glyph: '⌂',
    color: '#d78316',
    coordinates: [-75.5797, 6.2363],
    zoom: 17.2,
    pitch: 68,
    bearing: 24,
    eyebrow: 'Paisaje y patrimonio',
    fact: 'El Cerro Nutibara fue el primer cerro tutelar de Medellín, tiene 33,33 hectáreas y alberga la réplica arquitectónica del Pueblito Paisa.',
    valuationLens: 'El paisaje, las visuales, el patrimonio y la actividad turística son atributos de entorno que deben analizarse junto con accesibilidad, usos y conservación.',
    source: 'Alcaldía de Medellín · Secretaría de Medio Ambiente',
    challenge: {
      prompt: 'En una lectura valuatoria, ¿qué condición es especialmente relevante en este punto?',
      choices: ['Valor paisajístico y patrimonial', 'Actividad portuaria', 'Vocación industrial pesada'],
      answer: 0,
      explanation: 'El cerro combina paisaje, memoria urbana, turismo y patrimonio arquitectónico.',
    },
  },
  {
    id: 'comuna-13',
    name: 'Escaleras eléctricas de la Comuna 13',
    shortName: 'Comuna 13',
    icon: 'community',
    glyph: '↗',
    color: '#e34f7a',
    coordinates: [-75.6215, 6.2566],
    zoom: 17.2,
    pitch: 66,
    bearing: 42,
    eyebrow: 'Accesibilidad e identidad',
    fact: 'Sus seis tramos mejoraron la movilidad en una ladera de fuertes pendientes; el arte urbano y la actividad comunitaria consolidaron una nueva centralidad turística.',
    valuationLens: 'La accesibilidad efectiva, la pendiente, el flujo de visitantes y la transformación del espacio público influyen en el análisis de usos y dinámicas comerciales.',
    source: 'Alcaldía de Medellín · Secretaría de Comunicaciones',
    challenge: {
      prompt: '¿Cuál fue uno de los efectos directos de las escaleras eléctricas?',
      choices: ['Mejorar el acceso a las partes altas', 'Trasladar el río Medellín', 'Eliminar el transporte público'],
      answer: 0,
      explanation: 'La infraestructura redujo barreras de movilidad y mejoró el acceso cotidiano a servicios y oportunidades.',
    },
  },
  {
    id: 'plaza-botero',
    name: 'Plaza Botero y Museo de Antioquia',
    shortName: 'Plaza Botero',
    icon: 'art',
    glyph: '◆',
    color: '#7c5ce7',
    coordinates: [-75.5685, 6.252],
    zoom: 17.1,
    pitch: 64,
    bearing: -34,
    eyebrow: 'Arte y centralidad',
    fact: 'La plaza reúne 23 esculturas monumentales de Fernando Botero en cerca de 7.500 m², junto al Museo de Antioquia y el Palacio de la Cultura.',
    valuationLens: 'La mezcla de patrimonio, cultura, comercio, transporte y alta afluencia produce una centralidad compleja: no basta con comparar área y precio.',
    source: 'Alcaldía de Medellín · Guía de ciudad',
    challenge: {
      prompt: '¿Cuántas esculturas monumentales de Botero reúne la plaza?',
      choices: ['12', '23', '41'],
      answer: 1,
      explanation: 'Son 23 obras de bronce donadas por el artista medellinense.',
    },
  },
  {
    id: 'jardin-explora',
    name: 'Jardín Botánico y distrito Explora',
    shortName: 'Jardín–Explora',
    icon: 'nature',
    glyph: '✿',
    color: '#22a878',
    coordinates: [-75.5657, 6.2705],
    zoom: 16.8,
    pitch: 63,
    bearing: 18,
    eyebrow: 'Naturaleza y conocimiento',
    fact: 'En la zona norte convergen Jardín Botánico, Parque Explora, Planetario, Parque de los Deseos y Parque Norte, formando un corredor educativo y recreativo.',
    valuationLens: 'La proximidad a equipamientos, zonas verdes y transporte amplía las posibilidades de uso y la calidad urbana del entorno.',
    source: 'Alcaldía de Medellín · Catálogo de equipamientos',
    challenge: {
      prompt: '¿Qué concepto valuatorio ayuda a leer mejor esta concentración de equipamientos?',
      choices: ['Sinergia de localización', 'Depreciación física automática', 'Aislamiento funcional'],
      answer: 0,
      explanation: 'La cercanía entre equipamientos culturales, científicos, ambientales y de transporte crea una sinergia territorial.',
    },
  },
  {
    id: 'santo-domingo',
    name: 'Santo Domingo y Metrocable Línea K',
    shortName: 'Santo Domingo',
    icon: 'mobility',
    glyph: '◇',
    color: '#ef8c2f',
    coordinates: [-75.5429, 6.2943],
    zoom: 16.4,
    pitch: 69,
    bearing: -28,
    eyebrow: 'Movilidad y ladera',
    fact: 'La Línea K conectó el corredor nororiental con el sistema Metro y se convirtió en pieza central de una transformación urbana de alcance territorial.',
    valuationLens: 'En ladera, el tiempo real de acceso, la pendiente y la conexión con transporte masivo pueden ser tan importantes como la distancia en línea recta.',
    source: 'Alcaldía de Medellín · Planeación Municipal',
    challenge: {
      prompt: 'Para comparar inmuebles en ladera, ¿qué variable debe observarse con especial cuidado?',
      choices: ['Solo la distancia horizontal', 'Accesibilidad y tiempo de conexión', 'Únicamente el color de fachada'],
      answer: 1,
      explanation: 'La accesibilidad combina pendiente, recorridos peatonales y conexión efectiva al transporte.',
    },
  },
  {
    id: 'mamm-ciudad-del-rio',
    name: 'Museo de Arte Moderno y Ciudad del Río',
    shortName: 'MAMM · Ciudad del Río',
    icon: 'art',
    glyph: '▱',
    color: '#d75a45',
    coordinates: [-75.5748, 6.2238],
    zoom: 17.1,
    pitch: 65,
    bearing: -22,
    eyebrow: 'Renovación y cultura',
    fact: 'La antigua zona industrial de Simesa se transformó en un barrio mixto; el edificio Talleres Robledo fue recuperado como sede del Museo de Arte Moderno y abrió allí en 2009.',
    valuationLens: 'La reconversión de suelo industrial, la mezcla de vivienda, oficinas, comercio, cultura y espacio público modifica los usos posibles y la percepción de localización.',
    source: 'Museo de Arte Moderno de Medellín · Historia de Ciudad del Río',
    challenge: {
      prompt: '¿Qué proceso urbano representa mejor la transformación de Ciudad del Río?',
      choices: ['Renovación de un sector industrial', 'Expansión agrícola', 'Aislamiento de usos'],
      answer: 0,
      explanation: 'El sector pasó de una vocación industrial a una mezcla urbana articulada alrededor de vivienda, servicios, cultura y espacio público.',
    },
  },
  {
    id: 'parque-arvi',
    name: 'Parque Arví y Cable Turístico',
    shortName: 'Parque Arví',
    icon: 'nature',
    glyph: '♧',
    color: '#328b57',
    coordinates: [-75.5026, 6.3375],
    zoom: 15.5,
    pitch: 64,
    bearing: 28,
    eyebrow: 'Borde rural y conservación',
    fact: 'El Parque Arví es un parque público de 1.761 hectáreas de bosque, vinculado a la reserva del río Nare y al territorio rural de Santa Elena.',
    valuationLens: 'En el borde urbano-rural importan las restricciones ambientales, el acceso, la vocación del suelo, los servicios ecosistémicos y la relación con las comunidades locales.',
    source: 'Corporación Parque Arví · Qué es el Parque Arví',
    challenge: {
      prompt: '¿Qué variable debe revisarse primero al analizar un predio cercano a un área protegida?',
      choices: ['Restricciones y vocación ambiental', 'Color de la cubierta', 'Número de anuncios publicados'],
      answer: 0,
      explanation: 'La norma de uso y protección ambiental condiciona el aprovechamiento posible del suelo y debe verificarse antes de comparar precios.',
    },
  },
  {
    id: 'tranvia-ayacucho',
    name: 'Tranvía de Ayacucho y corredor oriental',
    shortName: 'Tranvía de Ayacucho',
    icon: 'mobility',
    glyph: '↝',
    color: '#e29d27',
    coordinates: [-75.5617, 6.2428],
    zoom: 16.9,
    pitch: 66,
    bearing: 38,
    eyebrow: 'Movilidad y corredor urbano',
    fact: 'El Tranvía de Ayacucho conecta el centro con el oriente y se integra con los cables de las líneas H y M, ampliando la accesibilidad de sectores de ladera.',
    valuationLens: 'La proximidad al transporte masivo puede aumentar accesibilidad y flujo peatonal, pero debe leerse junto con ruido, intensidad comercial, topografía y usos del corredor.',
    source: 'Metro de Medellín · Sistema Tranvía y cables complementarios',
    challenge: {
      prompt: '¿Qué efecto territorial es más directo alrededor de una estación de transporte masivo?',
      choices: ['Mejora de accesibilidad', 'Desaparición de la pendiente', 'Uniformidad automática de precios'],
      answer: 0,
      explanation: 'El transporte reduce tiempos de conexión, aunque cada inmueble conserva diferencias de uso, estado, topografía y entorno inmediato.',
    },
  },
  {
    id: 'atanasio-girardot',
    name: 'Unidad Deportiva Atanasio Girardot',
    shortName: 'Atanasio Girardot',
    icon: 'community',
    glyph: '◎',
    color: '#3c7fd6',
    coordinates: [-75.5901, 6.2569],
    zoom: 16.8,
    pitch: 64,
    bearing: -18,
    eyebrow: 'Deporte y grandes eventos',
    fact: 'El estadio fue inaugurado en 1953 y articula una unidad deportiva que reúne escenarios de fútbol, atletismo, natación y otras prácticas, además de eventos de gran formato.',
    valuationLens: 'Los grandes equipamientos atraen actividad y comercio en fechas específicas; conviene diferenciar el movimiento cotidiano de los picos generados por eventos.',
    source: 'Alcaldía de Medellín e INDER · Historia del Atanasio Girardot',
    challenge: {
      prompt: '¿Qué debe evitarse al valorar un local cercano a un gran escenario deportivo?',
      choices: ['Proyectar un día de evento como si fuera demanda permanente', 'Revisar accesos peatonales', 'Analizar usos vecinos'],
      answer: 0,
      explanation: 'La afluencia extraordinaria no representa por sí sola el comportamiento comercial de todos los días.',
    },
  },
  {
    id: 'alpujarra',
    name: 'Centro Administrativo La Alpujarra',
    shortName: 'La Alpujarra',
    icon: 'community',
    glyph: '▦',
    color: '#607d8b',
    coordinates: [-75.5746, 6.2433],
    zoom: 17,
    pitch: 65,
    bearing: 26,
    eyebrow: 'Centralidad institucional',
    fact: 'La Alpujarra concentra servicios administrativos y se conecta con estaciones de metro, metrobús y corredores que enlazan distintos sectores de la ciudad.',
    valuationLens: 'La concentración institucional genera demanda de oficinas, trámites y servicios; el análisis debe observar horarios, accesos, espacio público y mezcla de actividades vecinas.',
    source: 'Alcaldía de Medellín · Catálogo de equipamientos de La Candelaria',
    challenge: {
      prompt: '¿Qué uso suele beneficiarse directamente de una centralidad administrativa?',
      choices: ['Servicios y oficinas', 'Explotación forestal', 'Agricultura extensiva'],
      answer: 0,
      explanation: 'La presencia de entidades públicas favorece actividades profesionales, comercio de apoyo y servicios relacionados con trámites.',
    },
  },
  {
    id: 'museo-el-castillo',
    name: 'Museo El Castillo y sus jardines',
    shortName: 'Museo El Castillo',
    icon: 'heritage',
    glyph: '♜',
    color: '#8b6a4d',
    coordinates: [-75.5688, 6.1909],
    zoom: 17,
    pitch: 66,
    bearing: -30,
    eyebrow: 'Arquitectura y patrimonio',
    fact: 'La edificación fue construida en 1930 e inspirada en los castillos del Valle del Loira; hoy conserva colecciones de artes decorativas, salones y jardines abiertos como museo.',
    valuationLens: 'El valor patrimonial exige analizar conservación, restricciones de intervención, singularidad arquitectónica, paisaje y uso cultural, además del suelo y el área construida.',
    source: 'Museo El Castillo · Historia institucional',
    challenge: {
      prompt: '¿Qué enfoque es más adecuado para un inmueble patrimonial singular?',
      choices: ['Combinar conservación, singularidad y uso permitido', 'Usar solo el precio promedio del barrio', 'Ignorar sus jardines y contexto'],
      answer: 0,
      explanation: 'Un bien singular no se explica con un único promedio: requiere interpretar atributos arquitectónicos, normativos, culturales y de entorno.',
    },
  },
];
